/********************************************************************************
** Form generated from reading UI file 'mydialog.ui'
**
** Created by: Qt User Interface Compiler version 5.10.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MYDIALOG_H
#define UI_MYDIALOG_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QDialog>
#include <QtWidgets/QFormLayout>
#include <QtWidgets/QGridLayout>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHBoxLayout>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLCDNumber>
#include <QtWidgets/QLabel>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QScrollArea>
#include <QtWidgets/QSlider>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QTableWidget>
#include <QtWidgets/QTextEdit>
#include <QtWidgets/QToolButton>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MyDialog
{
public:
    QHBoxLayout *horizontalLayout;
    QGridLayout *gridLayout;
    QScrollArea *scrollArea;
    QWidget *scWidget;
    QLabel *imgLabel;
    QTextEdit *MyTxtBrowse;
    QGroupBox *groupBox_7;
    QGroupBox *lcdBox;
    QLCDNumber *lcdX;
    QLCDNumber *lcdY;
    QLCDNumber *obsX;
    QLCDNumber *obsY;
    QLabel *label_4;
    QLabel *label_5;
    QLabel *label_6;
    QLCDNumber *PIDintensity;
    QLCDNumber *lcdI;
    QLabel *ScaleLabel;
    QTableWidget *tableWidget;
    QToolButton *LayerUP;
    QToolButton *LayerDown;
    QPushButton *Push_Zin;
    QPushButton *Push_Zout;
    QGroupBox *groupBox_2;
    QSpinBox *MaxSpin;
    QLabel *label_7;
    QSpinBox *MinSpin;
    QLabel *label_8;
    QLabel *label;
    QSlider *BrightSlide;
    QPushButton *LoadPID;
    QLabel *label_9;
    QLabel *label_11;
    QLabel *label_3;
    QLabel *label_2;
    QGroupBox *groupBox_3;
    QFormLayout *formLayout;
    QPushButton *gridZero;
    QPushButton *grid3;
    QPushButton *grid5;
    QPushButton *grid8;
    QPushButton *gridColorButton;
    QPushButton *grid4;
    QGroupBox *groupBox_4;
    QPushButton *ReadDotImageBTN;
    QPushButton *NewDotImageBTN;
    QGroupBox *groupBox_5;
    QPushButton *Eraser1x1BTN;
    QPushButton *Eraser3x3BTN;
    QPushButton *Eraser5x5BTN;
    QPushButton *Eraser9x9BTN;
    QGroupBox *groupBox_6;
    QFormLayout *formLayout_2;
    QPushButton *DotViewSW;
    QLabel *DotDrawLabel;
    QPushButton *DotColorBTN;
    QLabel *dotColorLabel;
    QPushButton *DotSaveBTN;
    QGroupBox *cctlBox;
    QPushButton *CorrectBTN;
    QPushButton *acceptBTN;
    QPushButton *rejectBTN;
    QGroupBox *LegendBox;
    QLabel *leg1label;
    QLabel *leg2label;
    QLabel *leg3label;

    void setupUi(QDialog *MyDialog)
    {
        if (MyDialog->objectName().isEmpty())
            MyDialog->setObjectName(QStringLiteral("MyDialog"));
        MyDialog->resize(1280, 984);
        QSizePolicy sizePolicy(QSizePolicy::Preferred, QSizePolicy::Preferred);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(MyDialog->sizePolicy().hasHeightForWidth());
        MyDialog->setSizePolicy(sizePolicy);
        MyDialog->setMinimumSize(QSize(1280, 960));
        MyDialog->setMaximumSize(QSize(1280, 984));
        MyDialog->setSizeIncrement(QSize(1, 1));
        QPalette palette;
        QBrush brush(QColor(0, 0, 0, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QBrush brush1(QColor(220, 220, 220, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Button, brush1);
        QBrush brush2(QColor(255, 255, 255, 255));
        brush2.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Light, brush2);
        QBrush brush3(QColor(237, 237, 237, 255));
        brush3.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        QBrush brush4(QColor(110, 110, 110, 255));
        brush4.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Dark, brush4);
        QBrush brush5(QColor(147, 147, 147, 255));
        brush5.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Active, QPalette::Text, brush);
        palette.setBrush(QPalette::Active, QPalette::BrightText, brush2);
        palette.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Active, QPalette::Base, brush2);
        palette.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette.setBrush(QPalette::Active, QPalette::AlternateBase, brush3);
        QBrush brush6(QColor(255, 255, 220, 255));
        brush6.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::ToolTipBase, brush6);
        palette.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette.setBrush(QPalette::Inactive, QPalette::Midlight, brush3);
        palette.setBrush(QPalette::Inactive, QPalette::Dark, brush4);
        palette.setBrush(QPalette::Inactive, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette.setBrush(QPalette::Inactive, QPalette::BrightText, brush2);
        palette.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Base, brush2);
        palette.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush3);
        palette.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush6);
        palette.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::Midlight, brush3);
        palette.setBrush(QPalette::Disabled, QPalette::Dark, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Disabled, QPalette::Text, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::BrightText, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush6);
        palette.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        MyDialog->setPalette(palette);
        QFont font;
        font.setPointSize(8);
        MyDialog->setFont(font);
        MyDialog->setCursor(QCursor(Qt::ArrowCursor));
        MyDialog->setAcceptDrops(true);
        MyDialog->setAutoFillBackground(false);
        MyDialog->setSizeGripEnabled(true);
        MyDialog->setModal(true);
        horizontalLayout = new QHBoxLayout(MyDialog);
        horizontalLayout->setSpacing(3);
        horizontalLayout->setContentsMargins(1, 1, 1, 1);
        horizontalLayout->setObjectName(QStringLiteral("horizontalLayout"));
        horizontalLayout->setContentsMargins(5, 5, 5, 5);
        gridLayout = new QGridLayout();
        gridLayout->setSpacing(1);
        gridLayout->setObjectName(QStringLiteral("gridLayout"));
        gridLayout->setSizeConstraint(QLayout::SetNoConstraint);
        gridLayout->setContentsMargins(1, 1, 1, 1);
        scrollArea = new QScrollArea(MyDialog);
        scrollArea->setObjectName(QStringLiteral("scrollArea"));
        sizePolicy.setHeightForWidth(scrollArea->sizePolicy().hasHeightForWidth());
        scrollArea->setSizePolicy(sizePolicy);
        scrollArea->setMinimumSize(QSize(1100, 640));
        scrollArea->setMaximumSize(QSize(1100, 700));
        scrollArea->viewport()->setProperty("cursor", QVariant(QCursor(Qt::CrossCursor)));
        scrollArea->setMouseTracking(true);
        scrollArea->setStyleSheet(QStringLiteral(""));
        scrollArea->setFrameShape(QFrame::StyledPanel);
        scrollArea->setFrameShadow(QFrame::Sunken);
        scrollArea->setMidLineWidth(1);
        scrollArea->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOn);
        scrollArea->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOn);
        scrollArea->setSizeAdjustPolicy(QAbstractScrollArea::AdjustToContentsOnFirstShow);
        scrollArea->setWidgetResizable(false);
        scrollArea->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignTop);
        scWidget = new QWidget();
        scWidget->setObjectName(QStringLiteral("scWidget"));
        scWidget->setGeometry(QRect(0, 0, 400, 300));
        scWidget->setSizeIncrement(QSize(1, 1));
        scWidget->setCursor(QCursor(Qt::CrossCursor));
        scWidget->setMouseTracking(true);
        imgLabel = new QLabel(scWidget);
        imgLabel->setObjectName(QStringLiteral("imgLabel"));
        imgLabel->setGeometry(QRect(0, 0, 20, 20));
        imgLabel->setMinimumSize(QSize(20, 20));
        QPalette palette1;
        palette1.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette1.setBrush(QPalette::Active, QPalette::Button, brush);
        palette1.setBrush(QPalette::Active, QPalette::Light, brush);
        palette1.setBrush(QPalette::Active, QPalette::Midlight, brush);
        palette1.setBrush(QPalette::Active, QPalette::Dark, brush);
        palette1.setBrush(QPalette::Active, QPalette::Mid, brush);
        palette1.setBrush(QPalette::Active, QPalette::Text, brush2);
        palette1.setBrush(QPalette::Active, QPalette::BrightText, brush2);
        palette1.setBrush(QPalette::Active, QPalette::ButtonText, brush2);
        palette1.setBrush(QPalette::Active, QPalette::Base, brush);
        palette1.setBrush(QPalette::Active, QPalette::Window, brush);
        palette1.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette1.setBrush(QPalette::Active, QPalette::AlternateBase, brush);
        palette1.setBrush(QPalette::Active, QPalette::ToolTipBase, brush6);
        palette1.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette1.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Light, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Midlight, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Dark, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Mid, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Text, brush2);
        palette1.setBrush(QPalette::Inactive, QPalette::BrightText, brush2);
        palette1.setBrush(QPalette::Inactive, QPalette::ButtonText, brush2);
        palette1.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush6);
        palette1.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::WindowText, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::Light, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::Midlight, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::Dark, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::Mid, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::Text, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::BrightText, brush2);
        palette1.setBrush(QPalette::Disabled, QPalette::ButtonText, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::Window, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush6);
        palette1.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        imgLabel->setPalette(palette1);
        imgLabel->setCursor(QCursor(Qt::CrossCursor));
        imgLabel->setMouseTracking(true);
        imgLabel->setFocusPolicy(Qt::ClickFocus);
        imgLabel->setScaledContents(true);
        imgLabel->setTextInteractionFlags(Qt::NoTextInteraction);
        scrollArea->setWidget(scWidget);

        gridLayout->addWidget(scrollArea, 0, 0, 1, 1);

        MyTxtBrowse = new QTextEdit(MyDialog);
        MyTxtBrowse->setObjectName(QStringLiteral("MyTxtBrowse"));
        sizePolicy.setHeightForWidth(MyTxtBrowse->sizePolicy().hasHeightForWidth());
        MyTxtBrowse->setSizePolicy(sizePolicy);
        MyTxtBrowse->setMinimumSize(QSize(0, 40));
        MyTxtBrowse->setMaximumSize(QSize(16777215, 40));
        QFont font1;
        font1.setFamily(QStringLiteral("MS UI Gothic"));
        font1.setPointSize(9);
        MyTxtBrowse->setFont(font1);

        gridLayout->addWidget(MyTxtBrowse, 2, 0, 1, 2);

        groupBox_7 = new QGroupBox(MyDialog);
        groupBox_7->setObjectName(QStringLiteral("groupBox_7"));
        groupBox_7->setMinimumSize(QSize(0, 200));
        groupBox_7->setMaximumSize(QSize(16777215, 200));
        lcdBox = new QGroupBox(groupBox_7);
        lcdBox->setObjectName(QStringLiteral("lcdBox"));
        lcdBox->setGeometry(QRect(0, 20, 700, 50));
        lcdBox->setMinimumSize(QSize(0, 50));
        lcdBox->setMaximumSize(QSize(800, 80));
        QPalette palette2;
        QBrush brush7(QColor(0, 255, 0, 255));
        brush7.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::WindowText, brush7);
        palette2.setBrush(QPalette::Active, QPalette::Button, brush);
        palette2.setBrush(QPalette::Active, QPalette::Base, brush);
        palette2.setBrush(QPalette::Active, QPalette::Window, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::WindowText, brush7);
        palette2.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::WindowText, brush7);
        palette2.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::Window, brush);
        lcdBox->setPalette(palette2);
        lcdBox->setFont(font);
        lcdBox->setAutoFillBackground(false);
        lcdBox->setStyleSheet(QStringLiteral("background:black;"));
        lcdBox->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignTop);
        lcdBox->setFlat(false);
        lcdX = new QLCDNumber(lcdBox);
        lcdX->setObjectName(QStringLiteral("lcdX"));
        lcdX->setGeometry(QRect(20, 20, 50, 24));
        lcdX->setMinimumSize(QSize(50, 24));
        lcdX->setMaximumSize(QSize(50, 24));
        QPalette palette3;
        palette3.setBrush(QPalette::Active, QPalette::WindowText, brush7);
        palette3.setBrush(QPalette::Active, QPalette::Button, brush);
        palette3.setBrush(QPalette::Active, QPalette::Base, brush);
        palette3.setBrush(QPalette::Active, QPalette::Window, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::WindowText, brush7);
        palette3.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::WindowText, brush7);
        palette3.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::Window, brush);
        lcdX->setPalette(palette3);
        QFont font2;
        lcdX->setFont(font2);
        lcdX->setAutoFillBackground(false);
        lcdX->setStyleSheet(QStringLiteral("background:black;"));
        lcdX->setSegmentStyle(QLCDNumber::Flat);
        lcdY = new QLCDNumber(lcdBox);
        lcdY->setObjectName(QStringLiteral("lcdY"));
        lcdY->setGeometry(QRect(80, 20, 50, 24));
        lcdY->setMinimumSize(QSize(50, 24));
        lcdY->setMaximumSize(QSize(50, 24));
        QPalette palette4;
        palette4.setBrush(QPalette::Active, QPalette::WindowText, brush7);
        palette4.setBrush(QPalette::Active, QPalette::Button, brush);
        palette4.setBrush(QPalette::Active, QPalette::Base, brush);
        palette4.setBrush(QPalette::Active, QPalette::Window, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::WindowText, brush7);
        palette4.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::Window, brush);
        QBrush brush8(QColor(120, 120, 120, 255));
        brush8.setStyle(Qt::SolidPattern);
        palette4.setBrush(QPalette::Disabled, QPalette::WindowText, brush8);
        palette4.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::Window, brush);
        lcdY->setPalette(palette4);
        lcdY->setFont(font2);
        lcdY->setStyleSheet(QStringLiteral("background:black;"));
        lcdY->setLineWidth(1);
        lcdY->setSegmentStyle(QLCDNumber::Flat);
        obsX = new QLCDNumber(lcdBox);
        obsX->setObjectName(QStringLiteral("obsX"));
        obsX->setGeometry(QRect(250, 20, 50, 24));
        obsX->setMinimumSize(QSize(50, 24));
        obsX->setMaximumSize(QSize(50, 24));
        QPalette palette5;
        QBrush brush9(QColor(255, 255, 0, 255));
        brush9.setStyle(Qt::SolidPattern);
        palette5.setBrush(QPalette::Active, QPalette::WindowText, brush9);
        palette5.setBrush(QPalette::Active, QPalette::Button, brush);
        palette5.setBrush(QPalette::Active, QPalette::Base, brush);
        palette5.setBrush(QPalette::Active, QPalette::Window, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::WindowText, brush9);
        palette5.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette5.setBrush(QPalette::Disabled, QPalette::WindowText, brush8);
        palette5.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette5.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette5.setBrush(QPalette::Disabled, QPalette::Window, brush);
        obsX->setPalette(palette5);
        obsX->setStyleSheet(QStringLiteral("background:black;"));
        obsX->setSegmentStyle(QLCDNumber::Flat);
        obsY = new QLCDNumber(lcdBox);
        obsY->setObjectName(QStringLiteral("obsY"));
        obsY->setGeometry(QRect(330, 20, 50, 24));
        obsY->setMinimumSize(QSize(50, 24));
        obsY->setMaximumSize(QSize(50, 24));
        QPalette palette6;
        palette6.setBrush(QPalette::Active, QPalette::WindowText, brush9);
        palette6.setBrush(QPalette::Active, QPalette::Button, brush);
        palette6.setBrush(QPalette::Active, QPalette::Base, brush);
        palette6.setBrush(QPalette::Active, QPalette::Window, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::WindowText, brush9);
        palette6.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette6.setBrush(QPalette::Disabled, QPalette::WindowText, brush8);
        palette6.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette6.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette6.setBrush(QPalette::Disabled, QPalette::Window, brush);
        obsY->setPalette(palette6);
        obsY->setStyleSheet(QStringLiteral("background:black;"));
        obsY->setSegmentStyle(QLCDNumber::Flat);
        label_4 = new QLabel(lcdBox);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(230, 20, 16, 24));
        label_4->setMinimumSize(QSize(0, 24));
        label_4->setMaximumSize(QSize(16777215, 24));
        QPalette palette7;
        palette7.setBrush(QPalette::Active, QPalette::WindowText, brush9);
        palette7.setBrush(QPalette::Active, QPalette::Button, brush);
        palette7.setBrush(QPalette::Active, QPalette::Midlight, brush);
        palette7.setBrush(QPalette::Active, QPalette::Dark, brush);
        palette7.setBrush(QPalette::Active, QPalette::Base, brush);
        palette7.setBrush(QPalette::Active, QPalette::Window, brush);
        palette7.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette7.setBrush(QPalette::Active, QPalette::AlternateBase, brush);
        palette7.setBrush(QPalette::Inactive, QPalette::WindowText, brush9);
        palette7.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette7.setBrush(QPalette::Inactive, QPalette::Midlight, brush);
        palette7.setBrush(QPalette::Inactive, QPalette::Dark, brush);
        palette7.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette7.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette7.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette7.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush);
        palette7.setBrush(QPalette::Disabled, QPalette::WindowText, brush9);
        palette7.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette7.setBrush(QPalette::Disabled, QPalette::Midlight, brush);
        palette7.setBrush(QPalette::Disabled, QPalette::Dark, brush);
        palette7.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette7.setBrush(QPalette::Disabled, QPalette::Window, brush);
        palette7.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette7.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush);
        label_4->setPalette(palette7);
        QFont font3;
        font3.setPointSize(12);
        label_4->setFont(font3);
        label_4->setStyleSheet(QStringLiteral("background:black;\\nforeground:red"));
        label_4->setFrameShadow(QFrame::Plain);
        label_5 = new QLabel(lcdBox);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(310, 20, 16, 24));
        label_5->setMinimumSize(QSize(0, 24));
        label_5->setMaximumSize(QSize(16777215, 24));
        QPalette palette8;
        palette8.setBrush(QPalette::Active, QPalette::WindowText, brush9);
        palette8.setBrush(QPalette::Active, QPalette::Button, brush);
        palette8.setBrush(QPalette::Active, QPalette::Base, brush);
        palette8.setBrush(QPalette::Active, QPalette::Window, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::WindowText, brush9);
        palette8.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette8.setBrush(QPalette::Disabled, QPalette::WindowText, brush9);
        palette8.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette8.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette8.setBrush(QPalette::Disabled, QPalette::Window, brush);
        label_5->setPalette(palette8);
        label_5->setFont(font3);
        label_5->setStyleSheet(QStringLiteral("background:black;foreground:red"));
        label_6 = new QLabel(lcdBox);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(400, 20, 78, 24));
        label_6->setMinimumSize(QSize(0, 24));
        label_6->setMaximumSize(QSize(16777215, 24));
        QPalette palette9;
        palette9.setBrush(QPalette::Active, QPalette::WindowText, brush9);
        palette9.setBrush(QPalette::Active, QPalette::Button, brush);
        palette9.setBrush(QPalette::Active, QPalette::Base, brush);
        palette9.setBrush(QPalette::Active, QPalette::Window, brush);
        palette9.setBrush(QPalette::Inactive, QPalette::WindowText, brush9);
        palette9.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette9.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette9.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette9.setBrush(QPalette::Disabled, QPalette::WindowText, brush9);
        palette9.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette9.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette9.setBrush(QPalette::Disabled, QPalette::Window, brush);
        label_6->setPalette(palette9);
        label_6->setFont(font3);
        label_6->setStyleSheet(QStringLiteral("background:black;foreground:red"));
        PIDintensity = new QLCDNumber(lcdBox);
        PIDintensity->setObjectName(QStringLiteral("PIDintensity"));
        PIDintensity->setGeometry(QRect(470, 20, 50, 24));
        PIDintensity->setMinimumSize(QSize(50, 24));
        PIDintensity->setMaximumSize(QSize(50, 24));
        QPalette palette10;
        palette10.setBrush(QPalette::Active, QPalette::WindowText, brush9);
        palette10.setBrush(QPalette::Active, QPalette::Button, brush);
        palette10.setBrush(QPalette::Active, QPalette::Base, brush);
        palette10.setBrush(QPalette::Active, QPalette::Window, brush);
        palette10.setBrush(QPalette::Inactive, QPalette::WindowText, brush9);
        palette10.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette10.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette10.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette10.setBrush(QPalette::Disabled, QPalette::WindowText, brush);
        palette10.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette10.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette10.setBrush(QPalette::Disabled, QPalette::Window, brush);
        PIDintensity->setPalette(palette10);
        PIDintensity->setStyleSheet(QStringLiteral("background:black;foreground:yellow;"));
        PIDintensity->setSegmentStyle(QLCDNumber::Flat);
        lcdI = new QLCDNumber(lcdBox);
        lcdI->setObjectName(QStringLiteral("lcdI"));
        lcdI->setGeometry(QRect(140, 20, 55, 24));
        lcdI->setMinimumSize(QSize(55, 24));
        lcdI->setMaximumSize(QSize(55, 24));
        QPalette palette11;
        palette11.setBrush(QPalette::Active, QPalette::WindowText, brush7);
        palette11.setBrush(QPalette::Active, QPalette::Button, brush);
        palette11.setBrush(QPalette::Active, QPalette::Light, brush2);
        QBrush brush10(QColor(227, 226, 227, 255));
        brush10.setStyle(Qt::SolidPattern);
        palette11.setBrush(QPalette::Active, QPalette::Midlight, brush10);
        QBrush brush11(QColor(100, 99, 99, 255));
        brush11.setStyle(Qt::SolidPattern);
        palette11.setBrush(QPalette::Active, QPalette::Dark, brush11);
        QBrush brush12(QColor(133, 132, 133, 255));
        brush12.setStyle(Qt::SolidPattern);
        palette11.setBrush(QPalette::Active, QPalette::Mid, brush12);
        palette11.setBrush(QPalette::Active, QPalette::Text, brush);
        palette11.setBrush(QPalette::Active, QPalette::BrightText, brush2);
        palette11.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette11.setBrush(QPalette::Active, QPalette::Base, brush);
        palette11.setBrush(QPalette::Active, QPalette::Window, brush);
        palette11.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette11.setBrush(QPalette::Active, QPalette::AlternateBase, brush10);
        palette11.setBrush(QPalette::Active, QPalette::ToolTipBase, brush6);
        palette11.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette11.setBrush(QPalette::Inactive, QPalette::WindowText, brush7);
        palette11.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette11.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette11.setBrush(QPalette::Inactive, QPalette::Midlight, brush10);
        palette11.setBrush(QPalette::Inactive, QPalette::Dark, brush11);
        palette11.setBrush(QPalette::Inactive, QPalette::Mid, brush12);
        palette11.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette11.setBrush(QPalette::Inactive, QPalette::BrightText, brush2);
        palette11.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette11.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette11.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette11.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette11.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush10);
        palette11.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush6);
        palette11.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette11.setBrush(QPalette::Disabled, QPalette::WindowText, brush7);
        palette11.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette11.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette11.setBrush(QPalette::Disabled, QPalette::Midlight, brush10);
        palette11.setBrush(QPalette::Disabled, QPalette::Dark, brush11);
        palette11.setBrush(QPalette::Disabled, QPalette::Mid, brush12);
        palette11.setBrush(QPalette::Disabled, QPalette::Text, brush11);
        palette11.setBrush(QPalette::Disabled, QPalette::BrightText, brush2);
        palette11.setBrush(QPalette::Disabled, QPalette::ButtonText, brush11);
        palette11.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette11.setBrush(QPalette::Disabled, QPalette::Window, brush);
        palette11.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        QBrush brush13(QColor(200, 198, 199, 255));
        brush13.setStyle(Qt::SolidPattern);
        palette11.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush13);
        palette11.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush6);
        palette11.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        lcdI->setPalette(palette11);
        lcdI->setFont(font);
        lcdI->setStyleSheet(QStringLiteral("background:black;"));
        lcdI->setSegmentStyle(QLCDNumber::Flat);
        ScaleLabel = new QLabel(lcdBox);
        ScaleLabel->setObjectName(QStringLiteral("ScaleLabel"));
        ScaleLabel->setGeometry(QRect(570, 20, 88, 24));
        QPalette palette12;
        QBrush brush14(QColor(0, 255, 255, 255));
        brush14.setStyle(Qt::SolidPattern);
        palette12.setBrush(QPalette::Active, QPalette::WindowText, brush14);
        palette12.setBrush(QPalette::Active, QPalette::Button, brush);
        palette12.setBrush(QPalette::Active, QPalette::Base, brush);
        palette12.setBrush(QPalette::Active, QPalette::Window, brush);
        palette12.setBrush(QPalette::Inactive, QPalette::WindowText, brush14);
        palette12.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette12.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette12.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette12.setBrush(QPalette::Disabled, QPalette::WindowText, brush14);
        palette12.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette12.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette12.setBrush(QPalette::Disabled, QPalette::Window, brush);
        ScaleLabel->setPalette(palette12);
        ScaleLabel->setFont(font3);
        tableWidget = new QTableWidget(groupBox_7);
        if (tableWidget->columnCount() < 13)
            tableWidget->setColumnCount(13);
        QTableWidgetItem *__qtablewidgetitem = new QTableWidgetItem();
        tableWidget->setHorizontalHeaderItem(0, __qtablewidgetitem);
        QTableWidgetItem *__qtablewidgetitem1 = new QTableWidgetItem();
        tableWidget->setHorizontalHeaderItem(1, __qtablewidgetitem1);
        QTableWidgetItem *__qtablewidgetitem2 = new QTableWidgetItem();
        tableWidget->setHorizontalHeaderItem(2, __qtablewidgetitem2);
        QFont font4;
        font4.setBold(false);
        font4.setWeight(50);
        QTableWidgetItem *__qtablewidgetitem3 = new QTableWidgetItem();
        __qtablewidgetitem3->setFont(font4);
        tableWidget->setHorizontalHeaderItem(3, __qtablewidgetitem3);
        QTableWidgetItem *__qtablewidgetitem4 = new QTableWidgetItem();
        tableWidget->setHorizontalHeaderItem(4, __qtablewidgetitem4);
        QTableWidgetItem *__qtablewidgetitem5 = new QTableWidgetItem();
        tableWidget->setHorizontalHeaderItem(5, __qtablewidgetitem5);
        QTableWidgetItem *__qtablewidgetitem6 = new QTableWidgetItem();
        tableWidget->setHorizontalHeaderItem(6, __qtablewidgetitem6);
        if (tableWidget->rowCount() < 24)
            tableWidget->setRowCount(24);
        QTableWidgetItem *__qtablewidgetitem7 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(0, __qtablewidgetitem7);
        QTableWidgetItem *__qtablewidgetitem8 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(1, __qtablewidgetitem8);
        QTableWidgetItem *__qtablewidgetitem9 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(2, __qtablewidgetitem9);
        QTableWidgetItem *__qtablewidgetitem10 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(3, __qtablewidgetitem10);
        QTableWidgetItem *__qtablewidgetitem11 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(4, __qtablewidgetitem11);
        QTableWidgetItem *__qtablewidgetitem12 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(5, __qtablewidgetitem12);
        QTableWidgetItem *__qtablewidgetitem13 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(6, __qtablewidgetitem13);
        QTableWidgetItem *__qtablewidgetitem14 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(7, __qtablewidgetitem14);
        QTableWidgetItem *__qtablewidgetitem15 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(8, __qtablewidgetitem15);
        QTableWidgetItem *__qtablewidgetitem16 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(9, __qtablewidgetitem16);
        QTableWidgetItem *__qtablewidgetitem17 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(10, __qtablewidgetitem17);
        QTableWidgetItem *__qtablewidgetitem18 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(11, __qtablewidgetitem18);
        QTableWidgetItem *__qtablewidgetitem19 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(12, __qtablewidgetitem19);
        QTableWidgetItem *__qtablewidgetitem20 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(13, __qtablewidgetitem20);
        QTableWidgetItem *__qtablewidgetitem21 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(14, __qtablewidgetitem21);
        QTableWidgetItem *__qtablewidgetitem22 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(15, __qtablewidgetitem22);
        QTableWidgetItem *__qtablewidgetitem23 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(16, __qtablewidgetitem23);
        QTableWidgetItem *__qtablewidgetitem24 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(17, __qtablewidgetitem24);
        QTableWidgetItem *__qtablewidgetitem25 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(18, __qtablewidgetitem25);
        QTableWidgetItem *__qtablewidgetitem26 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(19, __qtablewidgetitem26);
        QTableWidgetItem *__qtablewidgetitem27 = new QTableWidgetItem();
        __qtablewidgetitem27->setFlags(Qt::ItemIsSelectable|Qt::ItemIsDragEnabled|Qt::ItemIsEnabled);
        tableWidget->setItem(0, 0, __qtablewidgetitem27);
        QTableWidgetItem *__qtablewidgetitem28 = new QTableWidgetItem();
        tableWidget->setItem(0, 3, __qtablewidgetitem28);
        QTableWidgetItem *__qtablewidgetitem29 = new QTableWidgetItem();
        __qtablewidgetitem29->setFlags(Qt::ItemIsSelectable|Qt::ItemIsDragEnabled|Qt::ItemIsEnabled);
        tableWidget->setItem(1, 0, __qtablewidgetitem29);
        QTableWidgetItem *__qtablewidgetitem30 = new QTableWidgetItem();
        __qtablewidgetitem30->setFlags(Qt::ItemIsSelectable|Qt::ItemIsDragEnabled|Qt::ItemIsEnabled);
        tableWidget->setItem(2, 0, __qtablewidgetitem30);
        QTableWidgetItem *__qtablewidgetitem31 = new QTableWidgetItem();
        __qtablewidgetitem31->setFlags(Qt::ItemIsSelectable|Qt::ItemIsDragEnabled|Qt::ItemIsEnabled);
        tableWidget->setItem(3, 0, __qtablewidgetitem31);
        tableWidget->setObjectName(QStringLiteral("tableWidget"));
        tableWidget->setGeometry(QRect(0, 70, 700, 121));
        sizePolicy.setHeightForWidth(tableWidget->sizePolicy().hasHeightForWidth());
        tableWidget->setSizePolicy(sizePolicy);
        tableWidget->setMaximumSize(QSize(800, 16777215));
        QFont font5;
        font5.setFamily(QStringLiteral("Arial Unicode MS"));
        font5.setPointSize(8);
        font5.setBold(false);
        font5.setWeight(50);
        tableWidget->setFont(font5);
        tableWidget->setFocusPolicy(Qt::NoFocus);
        tableWidget->setHorizontalScrollMode(QAbstractItemView::ScrollPerPixel);
        tableWidget->setRowCount(24);
        tableWidget->setColumnCount(13);
        tableWidget->horizontalHeader()->setDefaultSectionSize(80);
        tableWidget->horizontalHeader()->setHighlightSections(false);
        tableWidget->horizontalHeader()->setMinimumSectionSize(22);
        tableWidget->verticalHeader()->setVisible(true);
        tableWidget->verticalHeader()->setDefaultSectionSize(24);
        tableWidget->verticalHeader()->setMinimumSectionSize(20);
        LayerUP = new QToolButton(groupBox_7);
        LayerUP->setObjectName(QStringLiteral("LayerUP"));
        LayerUP->setGeometry(QRect(710, 80, 50, 40));
        LayerUP->setMinimumSize(QSize(50, 40));
        LayerUP->setMaximumSize(QSize(50, 40));
        LayerUP->setArrowType(Qt::UpArrow);
        LayerDown = new QToolButton(groupBox_7);
        LayerDown->setObjectName(QStringLiteral("LayerDown"));
        LayerDown->setGeometry(QRect(710, 130, 50, 40));
        LayerDown->setMinimumSize(QSize(50, 40));
        LayerDown->setMaximumSize(QSize(50, 40));
        LayerDown->setArrowType(Qt::DownArrow);
        Push_Zin = new QPushButton(groupBox_7);
        Push_Zin->setObjectName(QStringLiteral("Push_Zin"));
        Push_Zin->setGeometry(QRect(800, 20, 95, 28));
        QSizePolicy sizePolicy1(QSizePolicy::Fixed, QSizePolicy::Fixed);
        sizePolicy1.setHorizontalStretch(0);
        sizePolicy1.setVerticalStretch(0);
        sizePolicy1.setHeightForWidth(Push_Zin->sizePolicy().hasHeightForWidth());
        Push_Zin->setSizePolicy(sizePolicy1);
        Push_Zin->setMinimumSize(QSize(95, 0));
        Push_Zin->setMaximumSize(QSize(120, 16777215));
        QFont font6;
        font6.setFamily(QStringLiteral("MS Sans Serif"));
        font6.setPointSize(8);
        font6.setBold(true);
        font6.setWeight(75);
        Push_Zin->setFont(font6);
        Push_Zin->setFocusPolicy(Qt::NoFocus);
        Push_Zout = new QPushButton(groupBox_7);
        Push_Zout->setObjectName(QStringLiteral("Push_Zout"));
        Push_Zout->setGeometry(QRect(940, 20, 95, 28));
        Push_Zout->setMinimumSize(QSize(95, 0));
        Push_Zout->setMaximumSize(QSize(95, 16777215));
        Push_Zout->setFont(font6);
        Push_Zout->setFocusPolicy(Qt::NoFocus);
        groupBox_2 = new QGroupBox(groupBox_7);
        groupBox_2->setObjectName(QStringLiteral("groupBox_2"));
        groupBox_2->setGeometry(QRect(800, 60, 320, 131));
        groupBox_2->setMinimumSize(QSize(120, 120));
        groupBox_2->setMaximumSize(QSize(16777215, 16777215));
        groupBox_2->setFont(font6);
        groupBox_2->setLayoutDirection(Qt::LeftToRight);
        groupBox_2->setStyleSheet(QStringLiteral("border-color: rgb(0, 0, 0);"));
        groupBox_2->setAlignment(Qt::AlignCenter);
        groupBox_2->setFlat(false);
        MaxSpin = new QSpinBox(groupBox_2);
        MaxSpin->setObjectName(QStringLiteral("MaxSpin"));
        MaxSpin->setGeometry(QRect(220, 100, 70, 24));
        MaxSpin->setMinimumSize(QSize(70, 0));
        MaxSpin->setMaximumSize(QSize(70, 16777215));
        MaxSpin->setFocusPolicy(Qt::ClickFocus);
        MaxSpin->setButtonSymbols(QAbstractSpinBox::PlusMinus);
        MaxSpin->setAccelerated(true);
        MaxSpin->setKeyboardTracking(false);
        MaxSpin->setProperty("showGroupSeparator", QVariant(false));
        MaxSpin->setMaximum(65535);
        MaxSpin->setValue(4095);
        MaxSpin->setDisplayIntegerBase(10);
        label_7 = new QLabel(groupBox_2);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setGeometry(QRect(190, 100, 32, 16));
        label_7->setFont(font6);
        MinSpin = new QSpinBox(groupBox_2);
        MinSpin->setObjectName(QStringLiteral("MinSpin"));
        MinSpin->setGeometry(QRect(110, 100, 70, 24));
        MinSpin->setMaximumSize(QSize(70, 16777215));
        MinSpin->setFocusPolicy(Qt::ClickFocus);
        MinSpin->setAccelerated(true);
        MinSpin->setKeyboardTracking(false);
        MinSpin->setMaximum(40000);
        label_8 = new QLabel(groupBox_2);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(80, 100, 28, 16));
        label_8->setFont(font6);
        label = new QLabel(groupBox_2);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(10, 70, 40, 16));
        label->setFont(font6);
        BrightSlide = new QSlider(groupBox_2);
        BrightSlide->setObjectName(QStringLiteral("BrightSlide"));
        BrightSlide->setGeometry(QRect(60, 50, 231, 41));
        BrightSlide->setMouseTracking(true);
        BrightSlide->setFocusPolicy(Qt::NoFocus);
        BrightSlide->setLayoutDirection(Qt::LeftToRight);
        BrightSlide->setAutoFillBackground(false);
        BrightSlide->setMinimum(1);
        BrightSlide->setMaximum(200);
        BrightSlide->setSingleStep(1);
        BrightSlide->setPageStep(10);
        BrightSlide->setValue(100);
        BrightSlide->setSliderPosition(100);
        BrightSlide->setTracking(true);
        BrightSlide->setOrientation(Qt::Horizontal);
        BrightSlide->setInvertedAppearance(false);
        BrightSlide->setInvertedControls(false);
        BrightSlide->setTickPosition(QSlider::TicksAbove);
        BrightSlide->setTickInterval(20);
        LoadPID = new QPushButton(groupBox_2);
        LoadPID->setObjectName(QStringLiteral("LoadPID"));
        LoadPID->setGeometry(QRect(10, 10, 93, 24));
        sizePolicy.setHeightForWidth(LoadPID->sizePolicy().hasHeightForWidth());
        LoadPID->setSizePolicy(sizePolicy);
        LoadPID->setMaximumSize(QSize(800, 24));
        QFont font7;
        font7.setFamily(QStringLiteral("MS Sans Serif"));
        font7.setPointSize(8);
        font7.setBold(true);
        font7.setItalic(false);
        font7.setWeight(75);
        LoadPID->setFont(font7);
        LoadPID->setFocusPolicy(Qt::NoFocus);
        LoadPID->setStyleSheet(QStringLiteral(""));
        LoadPID->setText(QStringLiteral("Load"));
        label_9 = new QLabel(groupBox_2);
        label_9->setObjectName(QStringLiteral("label_9"));
        label_9->setGeometry(QRect(60, 40, 8, 15));
        label_9->setFont(font6);
        label_11 = new QLabel(groupBox_2);
        label_11->setObjectName(QStringLiteral("label_11"));
        label_11->setGeometry(QRect(160, 40, 24, 15));
        label_11->setFont(font6);
        label_3 = new QLabel(groupBox_2);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(270, 40, 37, 15));
        label_3->setFont(font6);
        label_2 = new QLabel(groupBox_2);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(10, 100, 50, 16));
        label_2->setFont(font6);
        groupBox_3 = new QGroupBox(groupBox_7);
        groupBox_3->setObjectName(QStringLiteral("groupBox_3"));
        groupBox_3->setGeometry(QRect(1130, 40, 111, 156));
        groupBox_3->setMaximumSize(QSize(136, 160));
        QFont font8;
        font8.setFamily(QStringLiteral("MS UI Gothic"));
        font8.setPointSize(9);
        font8.setBold(false);
        font8.setWeight(50);
        groupBox_3->setFont(font8);
        formLayout = new QFormLayout(groupBox_3);
        formLayout->setSpacing(2);
        formLayout->setContentsMargins(1, 1, 1, 1);
        formLayout->setObjectName(QStringLiteral("formLayout"));
        formLayout->setLabelAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        formLayout->setFormAlignment(Qt::AlignHCenter|Qt::AlignTop);
        formLayout->setHorizontalSpacing(4);
        formLayout->setVerticalSpacing(4);
        formLayout->setContentsMargins(2, 3, 6, 2);
        gridZero = new QPushButton(groupBox_3);
        gridZero->setObjectName(QStringLiteral("gridZero"));
        gridZero->setMinimumSize(QSize(0, 22));
        gridZero->setMaximumSize(QSize(100, 22));
        gridZero->setCheckable(true);
        gridZero->setAutoExclusive(false);

        formLayout->setWidget(0, QFormLayout::LabelRole, gridZero);

        grid3 = new QPushButton(groupBox_3);
        grid3->setObjectName(QStringLiteral("grid3"));
        grid3->setMinimumSize(QSize(0, 22));
        grid3->setMaximumSize(QSize(100, 22));
        grid3->setFocusPolicy(Qt::NoFocus);
        grid3->setCheckable(true);

        formLayout->setWidget(1, QFormLayout::LabelRole, grid3);

        grid5 = new QPushButton(groupBox_3);
        grid5->setObjectName(QStringLiteral("grid5"));
        grid5->setMinimumSize(QSize(0, 22));
        grid5->setMaximumSize(QSize(100, 22));
        grid5->setCheckable(true);

        formLayout->setWidget(3, QFormLayout::LabelRole, grid5);

        grid8 = new QPushButton(groupBox_3);
        grid8->setObjectName(QStringLiteral("grid8"));
        grid8->setMinimumSize(QSize(0, 22));
        grid8->setMaximumSize(QSize(100, 22));
        grid8->setCheckable(true);

        formLayout->setWidget(4, QFormLayout::LabelRole, grid8);

        gridColorButton = new QPushButton(groupBox_3);
        gridColorButton->setObjectName(QStringLiteral("gridColorButton"));
        gridColorButton->setMinimumSize(QSize(0, 22));
        gridColorButton->setMaximumSize(QSize(100, 22));
        gridColorButton->setFont(font);

        formLayout->setWidget(5, QFormLayout::LabelRole, gridColorButton);

        grid4 = new QPushButton(groupBox_3);
        grid4->setObjectName(QStringLiteral("grid4"));
        grid4->setMinimumSize(QSize(0, 22));
        grid4->setMaximumSize(QSize(100, 22));
        grid4->setCheckable(true);

        formLayout->setWidget(2, QFormLayout::LabelRole, grid4);


        gridLayout->addWidget(groupBox_7, 1, 0, 1, 2);

        groupBox_4 = new QGroupBox(MyDialog);
        groupBox_4->setObjectName(QStringLiteral("groupBox_4"));
        sizePolicy.setHeightForWidth(groupBox_4->sizePolicy().hasHeightForWidth());
        groupBox_4->setSizePolicy(sizePolicy);
        groupBox_4->setMinimumSize(QSize(120, 0));
        groupBox_4->setMaximumSize(QSize(148, 16777215));
        QFont font9;
        font9.setPointSize(11);
        groupBox_4->setFont(font9);
        groupBox_4->setLayoutDirection(Qt::LeftToRight);
        groupBox_4->setFlat(false);
        ReadDotImageBTN = new QPushButton(groupBox_4);
        ReadDotImageBTN->setObjectName(QStringLiteral("ReadDotImageBTN"));
        ReadDotImageBTN->setGeometry(QRect(10, 60, 80, 28));
        ReadDotImageBTN->setMinimumSize(QSize(80, 28));
        ReadDotImageBTN->setMaximumSize(QSize(80, 28));
        ReadDotImageBTN->setFont(font6);
        ReadDotImageBTN->setFocusPolicy(Qt::ClickFocus);
        NewDotImageBTN = new QPushButton(groupBox_4);
        NewDotImageBTN->setObjectName(QStringLiteral("NewDotImageBTN"));
        NewDotImageBTN->setGeometry(QRect(10, 30, 80, 28));
        NewDotImageBTN->setMinimumSize(QSize(80, 28));
        NewDotImageBTN->setMaximumSize(QSize(80, 28));
        NewDotImageBTN->setFont(font6);
        NewDotImageBTN->setFocusPolicy(Qt::ClickFocus);
        groupBox_5 = new QGroupBox(groupBox_4);
        groupBox_5->setObjectName(QStringLiteral("groupBox_5"));
        groupBox_5->setGeometry(QRect(10, 130, 80, 141));
        groupBox_5->setMaximumSize(QSize(80, 160));
        QFont font10;
        font10.setFamily(QStringLiteral("MS Sans Serif"));
        font10.setPointSize(8);
        font10.setBold(true);
        font10.setItalic(true);
        font10.setWeight(75);
        groupBox_5->setFont(font10);
        groupBox_5->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignTop);
        Eraser1x1BTN = new QPushButton(groupBox_5);
        Eraser1x1BTN->setObjectName(QStringLiteral("Eraser1x1BTN"));
        Eraser1x1BTN->setGeometry(QRect(10, 20, 60, 24));
        Eraser1x1BTN->setMinimumSize(QSize(60, 0));
        Eraser1x1BTN->setMaximumSize(QSize(60, 24));
        Eraser1x1BTN->setFocusPolicy(Qt::ClickFocus);
        Eraser1x1BTN->setCheckable(true);
        Eraser1x1BTN->setAutoExclusive(false);
        Eraser3x3BTN = new QPushButton(groupBox_5);
        Eraser3x3BTN->setObjectName(QStringLiteral("Eraser3x3BTN"));
        Eraser3x3BTN->setGeometry(QRect(10, 50, 60, 24));
        Eraser3x3BTN->setMinimumSize(QSize(60, 0));
        Eraser3x3BTN->setMaximumSize(QSize(60, 24));
        Eraser3x3BTN->setFocusPolicy(Qt::ClickFocus);
        Eraser3x3BTN->setCheckable(true);
        Eraser3x3BTN->setAutoExclusive(false);
        Eraser5x5BTN = new QPushButton(groupBox_5);
        Eraser5x5BTN->setObjectName(QStringLiteral("Eraser5x5BTN"));
        Eraser5x5BTN->setGeometry(QRect(10, 80, 60, 24));
        Eraser5x5BTN->setMinimumSize(QSize(60, 0));
        Eraser5x5BTN->setMaximumSize(QSize(60, 24));
        Eraser5x5BTN->setFocusPolicy(Qt::ClickFocus);
        Eraser5x5BTN->setCheckable(true);
        Eraser5x5BTN->setAutoExclusive(false);
        Eraser9x9BTN = new QPushButton(groupBox_5);
        Eraser9x9BTN->setObjectName(QStringLiteral("Eraser9x9BTN"));
        Eraser9x9BTN->setGeometry(QRect(10, 110, 60, 24));
        Eraser9x9BTN->setMinimumSize(QSize(60, 0));
        Eraser9x9BTN->setMaximumSize(QSize(60, 24));
        Eraser9x9BTN->setFocusPolicy(Qt::ClickFocus);
        Eraser9x9BTN->setCheckable(true);
        Eraser9x9BTN->setAutoExclusive(false);
        groupBox_6 = new QGroupBox(groupBox_4);
        groupBox_6->setObjectName(QStringLiteral("groupBox_6"));
        groupBox_6->setGeometry(QRect(0, 280, 140, 115));
        groupBox_6->setMinimumSize(QSize(100, 0));
        groupBox_6->setMaximumSize(QSize(140, 16777215));
        groupBox_6->setFont(font6);
        formLayout_2 = new QFormLayout(groupBox_6);
        formLayout_2->setSpacing(2);
        formLayout_2->setContentsMargins(1, 1, 1, 1);
        formLayout_2->setObjectName(QStringLiteral("formLayout_2"));
        DotViewSW = new QPushButton(groupBox_6);
        DotViewSW->setObjectName(QStringLiteral("DotViewSW"));
        DotViewSW->setMinimumSize(QSize(60, 0));
        DotViewSW->setMaximumSize(QSize(60, 16777215));
        QFont font11;
        font11.setFamily(QStringLiteral("Arial"));
        font11.setPointSize(6);
        font11.setBold(true);
        font11.setWeight(75);
        DotViewSW->setFont(font11);
        DotViewSW->setFocusPolicy(Qt::ClickFocus);

        formLayout_2->setWidget(0, QFormLayout::LabelRole, DotViewSW);

        DotDrawLabel = new QLabel(groupBox_6);
        DotDrawLabel->setObjectName(QStringLiteral("DotDrawLabel"));
        DotDrawLabel->setMinimumSize(QSize(45, 0));
        DotDrawLabel->setMaximumSize(QSize(45, 16777215));
        QFont font12;
        font12.setFamily(QStringLiteral("Arial"));
        DotDrawLabel->setFont(font12);
        DotDrawLabel->setFrameShape(QFrame::Panel);
        DotDrawLabel->setFrameShadow(QFrame::Sunken);
        DotDrawLabel->setLineWidth(3);
        DotDrawLabel->setAlignment(Qt::AlignCenter);

        formLayout_2->setWidget(0, QFormLayout::FieldRole, DotDrawLabel);

        DotColorBTN = new QPushButton(groupBox_6);
        DotColorBTN->setObjectName(QStringLiteral("DotColorBTN"));
        DotColorBTN->setMinimumSize(QSize(20, 20));
        DotColorBTN->setMaximumSize(QSize(60, 16777215));
        DotColorBTN->setFont(font11);
        DotColorBTN->setFocusPolicy(Qt::ClickFocus);

        formLayout_2->setWidget(1, QFormLayout::LabelRole, DotColorBTN);

        dotColorLabel = new QLabel(groupBox_6);
        dotColorLabel->setObjectName(QStringLiteral("dotColorLabel"));
        dotColorLabel->setMinimumSize(QSize(45, 40));
        dotColorLabel->setMaximumSize(QSize(45, 40));
        dotColorLabel->setCursor(QCursor(Qt::ArrowCursor));
        dotColorLabel->setFrameShape(QFrame::Panel);
        dotColorLabel->setFrameShadow(QFrame::Sunken);
        dotColorLabel->setLineWidth(2);

        formLayout_2->setWidget(1, QFormLayout::FieldRole, dotColorLabel);

        DotSaveBTN = new QPushButton(groupBox_4);
        DotSaveBTN->setObjectName(QStringLiteral("DotSaveBTN"));
        DotSaveBTN->setGeometry(QRect(10, 90, 80, 28));
        DotSaveBTN->setMinimumSize(QSize(0, 28));
        DotSaveBTN->setMaximumSize(QSize(80, 28));
        DotSaveBTN->setSizeIncrement(QSize(0, 0));
        DotSaveBTN->setFont(font6);
        DotSaveBTN->setFocusPolicy(Qt::ClickFocus);
        cctlBox = new QGroupBox(groupBox_4);
        cctlBox->setObjectName(QStringLiteral("cctlBox"));
        cctlBox->setEnabled(true);
        cctlBox->setGeometry(QRect(0, 390, 141, 111));
        cctlBox->setFont(font6);
        CorrectBTN = new QPushButton(cctlBox);
        CorrectBTN->setObjectName(QStringLiteral("CorrectBTN"));
        CorrectBTN->setEnabled(false);
        CorrectBTN->setGeometry(QRect(10, 20, 120, 28));
        CorrectBTN->setMaximumSize(QSize(120, 16777215));
        CorrectBTN->setFont(font6);
        acceptBTN = new QPushButton(cctlBox);
        acceptBTN->setObjectName(QStringLiteral("acceptBTN"));
        acceptBTN->setEnabled(false);
        acceptBTN->setGeometry(QRect(10, 50, 120, 28));
        rejectBTN = new QPushButton(cctlBox);
        rejectBTN->setObjectName(QStringLiteral("rejectBTN"));
        rejectBTN->setEnabled(false);
        rejectBTN->setGeometry(QRect(10, 80, 120, 28));
        LegendBox = new QGroupBox(groupBox_4);
        LegendBox->setObjectName(QStringLiteral("LegendBox"));
        LegendBox->setGeometry(QRect(0, 510, 111, 91));
        QFont font13;
        font13.setFamily(QStringLiteral("Arial"));
        font13.setPointSize(7);
        font13.setBold(true);
        font13.setWeight(75);
        LegendBox->setFont(font13);
        leg1label = new QLabel(LegendBox);
        leg1label->setObjectName(QStringLiteral("leg1label"));
        leg1label->setGeometry(QRect(20, 20, 80, 15));
        leg2label = new QLabel(LegendBox);
        leg2label->setObjectName(QStringLiteral("leg2label"));
        leg2label->setGeometry(QRect(20, 40, 80, 15));
        leg3label = new QLabel(LegendBox);
        leg3label->setObjectName(QStringLiteral("leg3label"));
        leg3label->setGeometry(QRect(20, 60, 80, 15));

        gridLayout->addWidget(groupBox_4, 0, 1, 1, 1);


        horizontalLayout->addLayout(gridLayout);

        QWidget::setTabOrder(ReadDotImageBTN, NewDotImageBTN);
        QWidget::setTabOrder(NewDotImageBTN, DotSaveBTN);
        QWidget::setTabOrder(DotSaveBTN, Eraser1x1BTN);
        QWidget::setTabOrder(Eraser1x1BTN, Eraser3x3BTN);
        QWidget::setTabOrder(Eraser3x3BTN, Eraser9x9BTN);
        QWidget::setTabOrder(Eraser9x9BTN, gridZero);
        QWidget::setTabOrder(gridZero, grid4);
        QWidget::setTabOrder(grid4, grid5);
        QWidget::setTabOrder(grid5, grid8);
        QWidget::setTabOrder(grid8, gridColorButton);
        QWidget::setTabOrder(gridColorButton, DotViewSW);
        QWidget::setTabOrder(DotViewSW, MyTxtBrowse);
        QWidget::setTabOrder(MyTxtBrowse, scrollArea);
        QWidget::setTabOrder(scrollArea, LayerUP);
        QWidget::setTabOrder(LayerUP, LayerDown);
        QWidget::setTabOrder(LayerDown, Eraser5x5BTN);

        retranslateUi(MyDialog);

        QMetaObject::connectSlotsByName(MyDialog);
    } // setupUi

    void retranslateUi(QDialog *MyDialog)
    {
        MyDialog->setWindowTitle(QApplication::translate("MyDialog", "MyDialog", nullptr));
        imgLabel->setText(QString());
        groupBox_7->setTitle(QApplication::translate("MyDialog", "Layer operation", nullptr));
        lcdBox->setTitle(QApplication::translate("MyDialog", "Viewport Information", nullptr));
        label_4->setText(QApplication::translate("MyDialog", "X:", nullptr));
        label_5->setText(QApplication::translate("MyDialog", "Y:", nullptr));
        label_6->setText(QApplication::translate("MyDialog", " Intensity", nullptr));
        ScaleLabel->setText(QApplication::translate("MyDialog", "Scale 1.00 x", nullptr));
        QTableWidgetItem *___qtablewidgetitem = tableWidget->horizontalHeaderItem(0);
        ___qtablewidgetitem->setText(QApplication::translate("MyDialog", "FileName", nullptr));
        QTableWidgetItem *___qtablewidgetitem1 = tableWidget->horizontalHeaderItem(1);
        ___qtablewidgetitem1->setText(QApplication::translate("MyDialog", "Base", nullptr));
        QTableWidgetItem *___qtablewidgetitem2 = tableWidget->horizontalHeaderItem(2);
        ___qtablewidgetitem2->setText(QApplication::translate("MyDialog", "Load", nullptr));
        QTableWidgetItem *___qtablewidgetitem3 = tableWidget->horizontalHeaderItem(3);
        ___qtablewidgetitem3->setText(QApplication::translate("MyDialog", "Draw", nullptr));
        QTableWidgetItem *___qtablewidgetitem4 = tableWidget->horizontalHeaderItem(4);
        ___qtablewidgetitem4->setText(QApplication::translate("MyDialog", "Switch", nullptr));
        QTableWidgetItem *___qtablewidgetitem5 = tableWidget->horizontalHeaderItem(5);
        ___qtablewidgetitem5->setText(QApplication::translate("MyDialog", "Color", nullptr));
        QTableWidgetItem *___qtablewidgetitem6 = tableWidget->horizontalHeaderItem(6);
        ___qtablewidgetitem6->setText(QApplication::translate("MyDialog", "setcolor", nullptr));
        QTableWidgetItem *___qtablewidgetitem7 = tableWidget->verticalHeaderItem(0);
        ___qtablewidgetitem7->setText(QApplication::translate("MyDialog", "[Layer1]", nullptr));
        QTableWidgetItem *___qtablewidgetitem8 = tableWidget->verticalHeaderItem(1);
        ___qtablewidgetitem8->setText(QApplication::translate("MyDialog", "[Layer2]", nullptr));
        QTableWidgetItem *___qtablewidgetitem9 = tableWidget->verticalHeaderItem(2);
        ___qtablewidgetitem9->setText(QApplication::translate("MyDialog", "[Layer3]", nullptr));
        QTableWidgetItem *___qtablewidgetitem10 = tableWidget->verticalHeaderItem(3);
        ___qtablewidgetitem10->setText(QApplication::translate("MyDialog", "[Layer4]", nullptr));
        QTableWidgetItem *___qtablewidgetitem11 = tableWidget->verticalHeaderItem(4);
        ___qtablewidgetitem11->setText(QApplication::translate("MyDialog", "[Layer5]", nullptr));
        QTableWidgetItem *___qtablewidgetitem12 = tableWidget->verticalHeaderItem(5);
        ___qtablewidgetitem12->setText(QApplication::translate("MyDialog", "[Layer6]", nullptr));
        QTableWidgetItem *___qtablewidgetitem13 = tableWidget->verticalHeaderItem(6);
        ___qtablewidgetitem13->setText(QApplication::translate("MyDialog", "[Layer7]", nullptr));
        QTableWidgetItem *___qtablewidgetitem14 = tableWidget->verticalHeaderItem(7);
        ___qtablewidgetitem14->setText(QApplication::translate("MyDialog", "[Layer8]", nullptr));
        QTableWidgetItem *___qtablewidgetitem15 = tableWidget->verticalHeaderItem(8);
        ___qtablewidgetitem15->setText(QApplication::translate("MyDialog", "[Layer9]", nullptr));
        QTableWidgetItem *___qtablewidgetitem16 = tableWidget->verticalHeaderItem(9);
        ___qtablewidgetitem16->setText(QApplication::translate("MyDialog", "[Layer10]", nullptr));
        QTableWidgetItem *___qtablewidgetitem17 = tableWidget->verticalHeaderItem(10);
        ___qtablewidgetitem17->setText(QApplication::translate("MyDialog", "[Layer11]", nullptr));
        QTableWidgetItem *___qtablewidgetitem18 = tableWidget->verticalHeaderItem(11);
        ___qtablewidgetitem18->setText(QApplication::translate("MyDialog", "[Layer12]", nullptr));
        QTableWidgetItem *___qtablewidgetitem19 = tableWidget->verticalHeaderItem(12);
        ___qtablewidgetitem19->setText(QApplication::translate("MyDialog", "[Layer13]", nullptr));
        QTableWidgetItem *___qtablewidgetitem20 = tableWidget->verticalHeaderItem(13);
        ___qtablewidgetitem20->setText(QApplication::translate("MyDialog", "[Layer14]", nullptr));
        QTableWidgetItem *___qtablewidgetitem21 = tableWidget->verticalHeaderItem(14);
        ___qtablewidgetitem21->setText(QApplication::translate("MyDialog", "[Layer15]", nullptr));
        QTableWidgetItem *___qtablewidgetitem22 = tableWidget->verticalHeaderItem(15);
        ___qtablewidgetitem22->setText(QApplication::translate("MyDialog", "[Layer16]", nullptr));
        QTableWidgetItem *___qtablewidgetitem23 = tableWidget->verticalHeaderItem(16);
        ___qtablewidgetitem23->setText(QApplication::translate("MyDialog", "[Layer17]", nullptr));
        QTableWidgetItem *___qtablewidgetitem24 = tableWidget->verticalHeaderItem(17);
        ___qtablewidgetitem24->setText(QApplication::translate("MyDialog", "[Layer18]", nullptr));
        QTableWidgetItem *___qtablewidgetitem25 = tableWidget->verticalHeaderItem(18);
        ___qtablewidgetitem25->setText(QApplication::translate("MyDialog", "[Layer19]", nullptr));
        QTableWidgetItem *___qtablewidgetitem26 = tableWidget->verticalHeaderItem(19);
        ___qtablewidgetitem26->setText(QApplication::translate("MyDialog", "[Layer20]", nullptr));

        const bool __sortingEnabled = tableWidget->isSortingEnabled();
        tableWidget->setSortingEnabled(false);
        tableWidget->setSortingEnabled(__sortingEnabled);

#ifndef QT_NO_TOOLTIP
        tableWidget->setToolTip(QApplication::translate("MyDialog", "control table-widget for Layer-image", nullptr));
#endif // QT_NO_TOOLTIP
#ifndef QT_NO_WHATSTHIS
        tableWidget->setWhatsThis(QApplication::translate("MyDialog", "You can read layer image, set visiblity of each layer,\n"
"and choose layer-image drawing color. ", nullptr));
#endif // QT_NO_WHATSTHIS
#ifndef QT_NO_TOOLTIP
        LayerUP->setToolTip(QApplication::translate("MyDialog", "change Layer-image sequence ", nullptr));
#endif // QT_NO_TOOLTIP
#ifndef QT_NO_WHATSTHIS
        LayerUP->setWhatsThis(QString());
#endif // QT_NO_WHATSTHIS
        LayerUP->setText(QApplication::translate("MyDialog", "...", nullptr));
#ifndef QT_NO_TOOLTIP
        LayerDown->setToolTip(QApplication::translate("MyDialog", "change Layer-image sequence ", nullptr));
#endif // QT_NO_TOOLTIP
        LayerDown->setText(QApplication::translate("MyDialog", "...", nullptr));
#ifndef QT_NO_TOOLTIP
        Push_Zin->setToolTip(QApplication::translate("MyDialog", "Zoom In operation for current viewport image", nullptr));
#endif // QT_NO_TOOLTIP
        Push_Zin->setText(QApplication::translate("MyDialog", "Zoom In   ", nullptr));
#ifndef QT_NO_TOOLTIP
        Push_Zout->setToolTip(QApplication::translate("MyDialog", "Zoom out operation for current viewport image", nullptr));
#endif // QT_NO_TOOLTIP
        Push_Zout->setText(QApplication::translate("MyDialog", "Zoom Out", nullptr));
#ifndef QT_NO_TOOLTIP
        groupBox_2->setToolTip(QApplication::translate("MyDialog", "tuning PID extraction range for creating PID image display data", nullptr));
#endif // QT_NO_TOOLTIP
        groupBox_2->setTitle(QApplication::translate("MyDialog", "BaseImage", nullptr));
        label_7->setText(QApplication::translate("MyDialog", "Max:", nullptr));
        label_8->setText(QApplication::translate("MyDialog", "Min:", nullptr));
        label->setText(QApplication::translate("MyDialog", "Bright", nullptr));
#ifndef QT_NO_TOOLTIP
        LoadPID->setToolTip(QApplication::translate("MyDialog", "Read PID image data\n"
"You must choose 16bit 3channel Tiff format data ", nullptr));
#endif // QT_NO_TOOLTIP
        label_9->setText(QApplication::translate("MyDialog", "0", nullptr));
        label_11->setText(QApplication::translate("MyDialog", "100", nullptr));
        label_3->setText(QApplication::translate("MyDialog", "200 %", nullptr));
        label_2->setText(QApplication::translate("MyDialog", "Range:", nullptr));
        groupBox_3->setTitle(QApplication::translate("MyDialog", "Grid Switch", nullptr));
        gridZero->setText(QApplication::translate("MyDialog", "None", nullptr));
        grid3->setText(QApplication::translate("MyDialog", "3 Grid", nullptr));
        grid5->setText(QApplication::translate("MyDialog", "5 Grid", nullptr));
        grid8->setText(QApplication::translate("MyDialog", "8 Grid", nullptr));
        gridColorButton->setText(QApplication::translate("MyDialog", "Grid Color", nullptr));
        grid4->setText(QApplication::translate("MyDialog", "4 Grid", nullptr));
        groupBox_4->setTitle(QApplication::translate("MyDialog", "Bright Spot Edit", nullptr));
#ifndef QT_NO_TOOLTIP
        ReadDotImageBTN->setToolTip(QApplication::translate("MyDialog", "Reading DotImage (PID positioning image data)", nullptr));
#endif // QT_NO_TOOLTIP
        ReadDotImageBTN->setText(QApplication::translate("MyDialog", "Load", nullptr));
#ifndef QT_NO_TOOLTIP
        NewDotImageBTN->setToolTip(QApplication::translate("MyDialog", "Create New Dot Image for PID positioning", nullptr));
#endif // QT_NO_TOOLTIP
        NewDotImageBTN->setText(QApplication::translate("MyDialog", "New", nullptr));
        groupBox_5->setTitle(QApplication::translate("MyDialog", "Eraser ", nullptr));
        Eraser1x1BTN->setText(QApplication::translate("MyDialog", "1x1", nullptr));
        Eraser3x3BTN->setText(QApplication::translate("MyDialog", "3x3", nullptr));
        Eraser5x5BTN->setText(QApplication::translate("MyDialog", "5x5", nullptr));
        Eraser9x9BTN->setText(QApplication::translate("MyDialog", "9x9", nullptr));
        groupBox_6->setTitle(QApplication::translate("MyDialog", "Disp", nullptr));
        DotViewSW->setText(QApplication::translate("MyDialog", "ON/OFF", nullptr));
        DotDrawLabel->setText(QApplication::translate("MyDialog", "ON", nullptr));
#ifndef QT_NO_TOOLTIP
        DotColorBTN->setToolTip(QApplication::translate("MyDialog", "Changing DotImage drawing color.\n"
"Reminds, DotImage color will be changed as white color when you saving the data.", nullptr));
#endif // QT_NO_TOOLTIP
        DotColorBTN->setText(QApplication::translate("MyDialog", "COLOR", nullptr));
        dotColorLabel->setText(QString());
#ifndef QT_NO_TOOLTIP
        DotSaveBTN->setToolTip(QApplication::translate("MyDialog", "Save DotImage ", nullptr));
#endif // QT_NO_TOOLTIP
        DotSaveBTN->setText(QApplication::translate("MyDialog", "Save", nullptr));
        cctlBox->setTitle(QApplication::translate("MyDialog", "Correct Control", nullptr));
        CorrectBTN->setText(QApplication::translate("MyDialog", "XY Correct", nullptr));
        acceptBTN->setText(QApplication::translate("MyDialog", "Accept result", nullptr));
        rejectBTN->setText(QApplication::translate("MyDialog", "Reject result", nullptr));
        LegendBox->setTitle(QApplication::translate("MyDialog", "Color sample", nullptr));
        leg1label->setText(QApplication::translate("MyDialog", " Same Point", nullptr));
        leg2label->setText(QApplication::translate("MyDialog", " Move Point", nullptr));
        leg3label->setText(QApplication::translate("MyDialog", " Duplicate", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MyDialog: public Ui_MyDialog {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MYDIALOG_H
